# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

QPADMslackcpp <- function(y, x, tau, penalty, a, lambda, pho = 5, maxstep = 1000L, eps = 0.001, intercept = FALSE) {
    .Call('_QPADMslack_QPADMslackcpp', PACKAGE = 'QPADMslack', y, x, tau, penalty, a, lambda, pho, maxstep, eps, intercept)
}

paraQPADMslackcpp <- function(y, x, K, tau, penalty, a, lambda, pho = 15, maxstep = 1000L, eps = 0.001, intercept = FALSE) {
    .Call('_QPADMslack_paraQPADMslackcpp', PACKAGE = 'QPADMslack', y, x, K, tau, penalty, a, lambda, pho, maxstep, eps, intercept)
}

